import { User, Post } from "./types"

export const currentUser: User = {
  id: "me",
  name: "田中 葵",
  username: "aoi_dance",
}

const users: User[] = [
  { id: "u1", name: "山田 さくら", username: "sakura_moves" },
  { id: "u2", name: "鈴木 蓮", username: "ren_freestyle" },
  { id: "u3", name: "中村 ひな", username: "hina_hiphop" },
  { id: "u4", name: "伊藤 そら", username: "sora_ballet" },
]

/** All users visible in search (following + non-following) */
export const allUsers: User[] = [
  ...users,
  { id: "u5", name: "佐藤 ゆい", username: "yui_bboy", bio: "B-Girl修行中🔥" },
  { id: "u6", name: "高橋 けんた", username: "kenta_popping", bio: "ポッピング専門。電気を流し続ける。" },
  { id: "u7", name: "渡辺 あおい", username: "aoi_jazz", bio: "ジャズダンス歴10年。表現を磨く毎日。" },
  { id: "u8", name: "小林 ゆうた", username: "yuta_lock", bio: "ロッキングで魂を解放する。" },
]

export const followingIds = new Set(["u1", "u2", "u3", "u4"])

const raw: Omit<Post, "id">[] = [
  {
    user: users[0],
    text: "今日はウェービングを重点的に練習した。肩の動きがようやく滑らかになってきた気がする。毎日地道にやるしかない💪",
    practiceMinutes: 90,
    createdAt: "2026-04-24T08:30:00Z",
    likes: 14,
    isLiked: false,
  },
  {
    user: users[1],
    text: "フリースタイルのバトルに向けて、アドリブ力を鍛え中。音楽に素直に反応できるよう意識してみた。",
    videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    practiceMinutes: 60,
    createdAt: "2026-04-24T07:15:00Z",
    likes: 28,
    isLiked: true,
  },
  {
    user: users[2],
    text: "ヒップホップの基礎に戻る日。グルーヴを体に染み込ませる感覚を大切に。",
    practiceMinutes: 45,
    createdAt: "2026-04-23T21:00:00Z",
    likes: 9,
    isLiked: false,
  },
  {
    user: users[3],
    text: "バレエのターンの練習。スポットがまだブレる。もっと体幹を使わないと。悔しいけど楽しい。",
    practiceMinutes: 120,
    createdAt: "2026-04-23T18:45:00Z",
    likes: 22,
    isLiked: false,
  },
  {
    user: users[0],
    text: "鏡の前で30分間ひたすら自撮りして振り付けの確認。客観的に見るの大事すぎる。",
    createdAt: "2026-04-22T20:00:00Z",
    likes: 5,
    isLiked: false,
  },
  {
    user: users[1],
    text: "友達とスタジオ入り。お互いにフィードバックし合うと気づきが全然違う。やっぱり仲間って最高。",
    videoUrl: "https://youtu.be/dQw4w9WgXcQ",
    practiceMinutes: 180,
    createdAt: "2026-04-22T15:30:00Z",
    likes: 41,
    isLiked: true,
  },
  {
    user: users[2],
    text: "今日は踊る気になれなかったけど、とりあえず音楽だけ聴きながらイメトレ。それでも大事な練習。",
    createdAt: "2026-04-21T22:10:00Z",
    likes: 33,
    isLiked: false,
  },
  {
    user: users[3],
    text: "発表会まであと2週間。振り付け完璧に入れたい。今日は通し稽古×5回。足が限界🔥",
    practiceMinutes: 150,
    createdAt: "2026-04-21T19:00:00Z",
    likes: 18,
    isLiked: false,
  },
  {
    user: users[0],
    text: "新しい曲でフリースタイル。最初の8カウントで止まってしまった。もっと引き出しを増やさないと。",
    practiceMinutes: 75,
    createdAt: "2026-04-20T21:30:00Z",
    likes: 7,
    isLiked: false,
  },
  {
    user: users[1],
    text: "アイソレーションを毎朝15分。地味だけど基礎が全てだと思ってる。",
    practiceMinutes: 15,
    createdAt: "2026-04-20T08:00:00Z",
    likes: 12,
    isLiked: false,
  },
  {
    user: users[2],
    text: "振り付けを覚えるのが苦手だったけど、スローで何度も反復する方法にしたら格段に良くなった。",
    practiceMinutes: 60,
    createdAt: "2026-04-19T20:45:00Z",
    likes: 25,
    isLiked: true,
  },
  {
    user: users[3],
    text: "ポアントで立つ練習。つま先の強化は終わりがない戦い。でも立てた瞬間の感覚は格別。",
    videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    practiceMinutes: 90,
    createdAt: "2026-04-19T17:00:00Z",
    likes: 37,
    isLiked: false,
  },
  {
    user: users[0],
    text: "今週は毎日スタジオに入れた。この継続が大事。来月のショーケースに向けて頑張る。",
    createdAt: "2026-04-18T22:00:00Z",
    likes: 20,
    isLiked: false,
  },
  {
    user: users[1],
    text: "ロッキングのファンクを研究中。YouTubeで70年代の動画を漁ってリスペクトを学ぶ。",
    practiceMinutes: 50,
    createdAt: "2026-04-18T16:20:00Z",
    likes: 15,
    isLiked: false,
  },
  {
    user: users[2],
    text: "グループでの練習。自分が一番下手だと感じる瞬間が一番成長できる。今日もたくさん気づきをもらった。",
    practiceMinutes: 120,
    createdAt: "2026-04-17T19:30:00Z",
    likes: 31,
    isLiked: true,
  },
  {
    user: users[3],
    text: "ストレッチだけで1時間。柔軟性が上がると動きが変わる。地道にやるか。",
    practiceMinutes: 60,
    createdAt: "2026-04-17T07:30:00Z",
    likes: 8,
    isLiked: false,
  },
  {
    user: users[0],
    text: "振り付けを作ってみた。最初の16カウントだけ。自分で作るって難しいし楽しい。",
    createdAt: "2026-04-16T21:00:00Z",
    likes: 19,
    isLiked: false,
  },
  {
    user: users[1],
    text: "雨でスタジオに行けなかったから部屋練。狭い空間でも工夫次第で十分練習になる。",
    practiceMinutes: 40,
    createdAt: "2026-04-16T14:00:00Z",
    likes: 11,
    isLiked: false,
  },
  {
    user: users[2],
    text: "コンテスト落ちた。悔しい。でも審査員のコメントがめちゃくちゃ参考になった。次につなげる。",
    createdAt: "2026-04-15T23:00:00Z",
    likes: 52,
    isLiked: true,
  },
  {
    user: users[3],
    text: "先生に「表情が硬い」と言われた。技術だけじゃなく表現力も磨かないとな。",
    practiceMinutes: 100,
    createdAt: "2026-04-15T18:00:00Z",
    likes: 26,
    isLiked: false,
  },
  {
    user: users[0],
    text: "動画を見返したら思ってたより全然できてなかった。現実を知ることの大切さよ。",
    videoUrl: "https://youtu.be/dQw4w9WgXcQ",
    practiceMinutes: 80,
    createdAt: "2026-04-14T20:30:00Z",
    likes: 16,
    isLiked: false,
  },
  {
    user: users[1],
    text: "パッピングの電流感。毎回うまくいくわけじゃないけど、ハマった瞬間が快感すぎる。",
    practiceMinutes: 70,
    createdAt: "2026-04-14T17:00:00Z",
    likes: 29,
    isLiked: false,
  },
  {
    user: users[2],
    text: "今日はひたすら音ハメの練習。リズムトレーニングを10年やってきた先輩に教えてもらった。",
    practiceMinutes: 90,
    createdAt: "2026-04-13T19:45:00Z",
    likes: 21,
    isLiked: true,
  },
  {
    user: users[3],
    text: "舞台照明の中で踊る練習。普段と全然違う。目が慣れるまで時間かかった。",
    createdAt: "2026-04-13T16:00:00Z",
    likes: 14,
    isLiked: false,
  },
  {
    user: users[0],
    text: "3ヶ月練習してきた曲、ついて完成させた。感無量。次の目標を決めないと。",
    videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    practiceMinutes: 110,
    createdAt: "2026-04-12T22:00:00Z",
    likes: 67,
    isLiked: false,
  },
  {
    user: users[1],
    text: "筋トレを練習に取り入れ始めた。体幹が弱いと何もできないって改めて感じた。",
    practiceMinutes: 45,
    createdAt: "2026-04-12T08:30:00Z",
    likes: 18,
    isLiked: false,
  },
  {
    user: users[2],
    text: "初めてのソロ発表。緊張しすぎて頭が白くなったけど、とにかく体が動いてくれた。",
    createdAt: "2026-04-11T21:30:00Z",
    likes: 44,
    isLiked: true,
  },
  {
    user: users[3],
    text: "ピルエット×3回転を初めて成功。今年の目標の一つクリア🎉",
    practiceMinutes: 80,
    createdAt: "2026-04-11T18:00:00Z",
    likes: 59,
    isLiked: false,
  },
  {
    user: users[0],
    text: "久しぶりに基礎だけの練習。うまくなりたいなら基礎。これに尽きる。",
    practiceMinutes: 60,
    createdAt: "2026-04-10T20:00:00Z",
    likes: 23,
    isLiked: false,
  },
  {
    user: users[1],
    text: "今月の練習時間の合計が30時間を超えた。数字にすると励みになる。",
    createdAt: "2026-04-10T09:00:00Z",
    likes: 35,
    isLiked: false,
  },
]

export const allPosts: Post[] = raw.map((p, i) => ({ ...p, id: `post-${i}` }))
